### ISSUE TITLE
Research path to get collection into galaxy

### ISSUE THREAD

**Issue by mpetrive-rh** [redhat-cop/tower_configuration#23]
Authentication requirements

Linting requirements

**Comment by sean-m-sullivan** [comment]
We have perm from the owners of redhat-cop but we will not get our own admin in there. So that path is open once we get a .0.0.1 version ready. With the final data structure.

**Comment by kdelee** [comment]
I see some other `tower_configuration` collections on galaxy, but I'm assuming that the `redhat-cop.tower_configuration` collection is still unpublished?

https://galaxy.ansible.com/search?deprecated=false&keywords=tower_configuration&order_by=-relevance&page=1

**Comment by kedark3** [comment]
@kdelee the one here : https://galaxy.ansible.com/tompage1994/tower_configuration is built from this repo only, but Tom did it to test how it was all working. The official one will be under https://galaxy.ansible.com/redhat_cop
(commenting in both places to have responses recorded as the other repo is private)

**Comment by sean-m-sullivan** [comment]
update to this, we have redhat_cop in galaxy now, a secret needs to be added to this for uploading to galaxy from our workflow, i have tested it for pushing to galaxy and the workflow works, just missing the credential.

**Comment by sean-m-sullivan** [comment]
We are now able to tag releases to go to galaxy, closing this issue.
