### ISSUE TITLE
How to contribute roles relying on Tower API 

### ISSUE THREAD

**Issue by oybed** [redhat-cop/tower_configuration#31]
Hi team.

We have a good set of Ansible Tower roles in [infra-ansible](https://github.com/redhat-cop/infra-ansible/tree/master/roles/ansible/tower) that relies on the Tower API rather than Ansible modules such as awx. We believe this is beneficial in many cases as it is very light weight and require very few dependencies. In the spirit of collaboration, we would like contribute these roles into this repo for re-use, but wondering how we could do this as there are many overlapping roles. The options as I see it are:

1) Combine roles with existing ones here and use an inventory flag to indicate if API should be used v.s. non-API
2) Keep a separate set of "API roles" - perhaps under `roles/api-based/<role>`
3) Anything else?

Any guidance and preference? 

CC @tonykay @tylerauerbeck @pabrahamsson @paulbarfuss

**Comment by kedark3** [comment]
@oybed thanks for the question. Initially this repo was destined to be designed on the top of collections. But I'd encourage you to attend our meeting where we can discuss this topic. It is Tuesday-Thursday 11am. Please ping me on Google Chat if you need an invite.

**Comment by sean-m-sullivan** [comment]
We discussed this in the meeting today. At least a few of us started out using things like infra-ansible. Especially with some of the failures of the unsupported tower-cli modules. or even as suplement to them. 
Part of the issue we found with using the pure URI is that
- it increases in complexity as you loop through objects. 
- python api calls are faster then multiple uri task calls
- it does not scale 

for example on scaling if you have tower workflows + schema, it currently takes 3 tasks to create it, and assuming 5 workflow nodes for each workflow, that is 15 tasks, then convert that to URI module it will likely take 10 tasks or more to complete the same as in 3 module tasks. So on loop that is 45 tasks, For each workflow. In addition maintaing those tasks is more complex. 

We would be all for doing uri modules on things that the awx/tower collection doesn't currently support. I think a good example of this is your ldap role, However I know some of us have been working in the background on the modules, and it would be a good candidate for a new module to create in the awx/tower collection.

**Comment by oybed** [comment]
@sean-m-sullivan @kedark3 while I understand that the approach you are preferring for the roles  may be a different direction than the roles we have, there are others that have a preference on using the APIs as part of the roles. It wasn't the intent of this particular issue to discuss technical preferences, but more about how we could potentially co-exist in the same repo. I understood the intent of this repo to be a way of grouping similar roles and avoid having multiple repos achieving the same thing. I'm sort of getting the sense that it may not necessarily be the case and only specific approaches will be accepted?

**Comment by jkupferer** [comment]
@oybed , I had a brief chat with @sean-m-sullivan after the meeting today. There seemed to be some confusion over the user of the `uri` module vs the cli vs the api. We are all on the same page as far as moving away from cli based management.

I believe issue is whether to use `uri` module to communicate with the api or to use modules written in Python that are part of the `awx` collection that communicate with the awx api. Those modules are not using the cli underneath like the old tower modules. I'm not sure where that will leave `infra-ansible`. My guess is that the direction should focus on building on top of the new modules?

**Comment by sean-m-sullivan** [comment]
I'm not fully against offering the option to people with the roles. We have been working with the idea that the roles would be best practices and that we would cut down on duplicate work being done across projects/customers. 

One of the guiding things we have been using in this project is a single data model, to describe tower objects. We gathered what was currently being used and came up with a format, but then talked with someone working with the ansible engineers that introduced us to the AWXkit tower export command being worked on. Leading to this. what you can find [here](https://github.com/redhat-cop/tower_configuration/tree/master/playbooks/json/export_models) 

If you were to submit PR's they would need to injest the data format found there, and we are moving all the roles over to work with that or a similar data model based on what we anticipate. This is based on the Tower API json + the related links found in the tower api. 

I think the best step forward would be to join one of our Tuesday/Thursday meetings and we can discuss it more with the group, Get your perspective and talk it over. As said we aren't against it, but do believe it would much more code to maintain, and had concerns.

**Comment by jkupferer** [comment]
@sean-m-sullivan The link above is broken, do you have an update?

**Comment by sean-m-sullivan** [comment]
Here is the link on the [Readme](https://github.com/redhat-cop/tower_configuration/blob/devel/playbooks/json/export_models/README.md) in the tower export model folder. This will be changing again with one of our PRs.  @jkupferer 

We currently have Workfows using the dual data model, and have a PR to do so for organizations. So its certainly possible to still do what you talked about above with using pure API's instead of the modules.

**Comment by sean-m-sullivan** [comment]
Since there has been no movement on this, we are closing this issue, If someone would want to write options for the roles to use the API they are welcome to contribute that method.
