### ISSUE TITLE
tower_group option

### ISSUE THREAD

**Issue by weiyentan** [redhat-cop/tower_configuration#44]
Is there an option to have tower_group? I can submit a PR for this feature that follows the setup you have

**Comment by sean-m-sullivan** [comment]
Generally we are using Dynamic Inventories, but we welcome Everything that configures tower. We just haven't gotten around to that one yet.

**Comment by weiyentan** [comment]
I would like to take this on. Will submit soon

**Comment by weiyentan** [comment]
This has been added into the role under pull request #54 . So closing this issue.
