### ISSUE TITLE
clarification on include_role:  name: ../..

### ISSUE THREAD

**Issue by weiyentan** [redhat-cop/tower_configuration#45]
In the readme they give this option. 

include_role: 
        name: ../..

I thought that this should be the role name that you have provided. In the case of inventory it would be inventory, host,

**Comment by sean-m-sullivan** [comment]
For the readme's we should update this to be the actual role names so people can copy paste the code. 

However I've looked at roughly 5 roles and didn't see it in the readme. 

Where it is in the tests/test.yml file where they are built to be functional, so you need to traverse up a folder and call the role the test file is in. There it is fine as the test.yml is built to be functional.

**Comment by weiyentan** [comment]
These are what I found on what they are on:
organizations
projects
workflow_job_templates

Thank you for looking into this. Its a very polished collection.

**Comment by sean-m-sullivan** [comment]
PR for this made here
https://github.com/redhat-cop/tower_configuration/pull/46

**Comment by kedark3** [comment]
#46 was merged. Closing this issue. If you feel its not adequately addressed please reopen.
