### ISSUE TITLE
Name Change to collection

### ISSUE THREAD

**Issue by Wilk42** [redhat-cop/tower_configuration#5]
It has been proposed to change the name of the collection. 
automate_tower_genie_collections

Some people don't like the name genie, others think its too long
An example of other collection names are:
community.kubernetes , where community is the galaxy designator. 

Perhaps automate_tower ? 

Keep in mind we would be using this in the namespace of the role for vars. 
tower_genie_credentials_secure_logging

**Comment by kedark3** [comment]
I support to have a vote for better naming. Ideas: 
- Ansible Tower Configuration-as-Code (ATCasC)  - Shameless plug
- Automate Tower
- Tower Auto-Configurations

**Comment by Wilk42** [comment]
complete
